### ISSUE TITLE
Better nested routing support?

### ISSUE THREAD

**Issue by RevillWeb** [RevillWeb/rebel-router#2]
Currently you are able to flag a router to `inherit` a parent routers current path like so:

``` html
<rebel-router inherit="true">
    <route path="/details">
        <p>General details for ${this.name}.</p>
    </route>
    <default><p>Use the nav above.</p></default>
</rebel-router>
```

This means that if the above router was a child of a route which had a path of `/user/{id}` then the above details example would be automatically registered as `/user/{id}/details` so that you don't have to specify the full path every time.

But to then navigate to this sub-route you would currently need to do this:

``` html
<a href="#/user/${this.id}/details">Details</a>
```

You'd have to specify the full path in the anchor to navigate to the sub-route - it wouldn't `inherit` like the router route does.

**The question is:** Would it be better to provide another element which extends the anchor tag so that the router can catch the click, prepend the inherited path and then navigate - basically allowing the anchors to also inherit routes. For example instead of the above you could do this:

``` html
<a href="/details" is="rebel-a">Details</a>
```

Or is there a better solution entirely?

**Comment by PixelsCommander** [comment]
Routes nesting should be as transparent as possible - if route is inside of other route it should be accessible by path which is a composition of parent route and route itself.

```
<router>
    <route path="A">
        <route path="B"></route>
    </route>
<router>
```

Means that second route should be accessible via A/B/. 

Explicit way to provide API you described is introducing shortcut attribute.

```
<router>
    <route path="A">
        <route path="B" shortcut="C"></route>
    </route>
<router>
```

Means that second route is going to be accessible via A/B or C.

**Comment by RevillWeb** [comment]
Thanks for your reply. So with the inherit attribute set to true that is the case (apart from the shortcut - which I like the idea of). The part I'm not sure about is what the user would expect when adding in anchors to navigate to the nested routes - does that make sense?

Do you also think that routes should be inherited by default? Instead of having to set inherit to true?

**Comment by PixelsCommander** [comment]
React Router behaves as:

```
<router>
    <route path="A"> /A/
        <route path="B"></route> /A/B/
    </route>
<router>
```

So this is what expected in most of cases.

**Comment by RevillWeb** [comment]
Hey,

This is exactly what it currently does (with the inherit attribute) - I think I'll change it to inherit automatically with the option to disable. 

But what about the anchors?

Would you expect this:

``` html
<router>
    <route path="A">
        <router>
            <route path="B">
                <a href="#/A/C">Go to A/C</a>
            </route>
            <route path="C">
                <a href="#/A/B">Go to A/B</a>
            </route>
        </router>
    </route>
</router>
```

Or this:

``` html
<router>
    <route path="A">
        <router>
            <route path="B">
                <a href="#/C" is="rebel-a">Go to A/C</a>
            </route>
            <route path="C">
                <a href="#/B" is="rebel-a">Go to A/B</a>
                <a href="#/D">Go to D</a>
            </route>
        </router>
    </route>
   <route path="D"></route>
</router>
```

I'm thinking the first is simpler however the user would have to reconstruct the URL including query parameters just to go to a route within that router instance.

I hope this example makes it clearer. Thanks!

**Comment by PixelsCommander** [comment]
First one looks more intuitive.

2016-06-21 13:51 GMT+02:00 Leon Revill notifications@github.com:

**Comment by RevillWeb** [comment]
Brilliant. Thanks for your time and input.
